build:
  image: fracting/msys32
  pull: true
  shell: msys32
  commands:
    - export RUNTEST=$$runtest
    - ./ci-build.sh

notify:
  irc:
    prefix: build
    nick: MINGW-packages
    channel: msys2-ci
    server:
      host: irc.oftc.net
      port: 6667

matrix:
  runtest:
    - false
# Temprorary disable matrix build to workaround irc plugin bug on wine-ci.org, see https://github.com/drone/drone/issues/1459
#    - true # allow failures
