build:
  image: teaci/msys$$arch
  pull: true
  shell: msys$$arch
  commands:
    - ./ci-build.sh

notify:
  irc:
    prefix: build
    nick: MINGW-packages
    channel: msys2-ci
    server:
      host: irc.oftc.net
      port: 6667

matrix:
  arch:
    - 64
    - 32
#FIXME: When a matrix build is done, only the build status of the last job in a matrix is sent to notification plugins, this confuses our irc plugin, see https://github.com/drone/drone/issues/1459. Github pull request Web UI status and Tea CI Web UI status works fine with matrix build.
