build:
  image: fracting/msys32
  shell: msys32
  commands:
    - drone/build.sh

notify:
  irc:
    prefix: build
    nick: MINGW-packages
    channel: msys2
    server:
      host: irc.oftc.net
      port: 6667
