trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

jobs:
  - job: MINGW
    timeoutInMinutes: 360
    pool:
      vmImage: vs2017-win2016
    strategy:
      maxParallel: 5
      matrix:
        i686:
          MINGW_UPPER: MINGW32
          MINGW_LOWER: mingw32
          MINGW_ARCH: i686
        x86_64:
          MINGW_UPPER: MINGW64
          MINGW_LOWER: mingw64
          MINGW_ARCH: x86_64
    steps:
      - powershell: |
          (New-Object Net.WebClient).DownloadFile("https://github.com/msys2/msys2-installer/releases/download/2020-05-22/msys2-base-x86_64-20200522.sfx.exe", "sfx.exe")
        displayName: Download MSYS2
      - script: |
          sfx.exe -y -o%CD:~0,2%\
          %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
          %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
        displayName: Extract/Install/Update MSYS2
      - script: |
          %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm --needed -S git base-devel mingw-w64-$(MINGW_ARCH)-toolchain"
          %CD:~0,2%\msys64\usr\bin\bash -lc "pacman --noconfirm -Scc"
        displayName: Install Toolchain
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\sed -i "s|#CacheDir.*|CacheDir=/c/Users/%USERNAME%/AppData/Local/Temp|g" /etc/pacman.conf
          %CD:~0,2%\msys64\usr\bin\bash -lc "bash ci-build.sh"
        displayName: CI-Build
        env:
          MSYSTEM: $(MINGW_UPPER)
          CHERE_INVOKING: yes
          MINGW_INSTALLS: $(MINGW_LOWER)
          BUILD_URL: dummy
          DEPLOY_PROVIDER: bintray
          BINTRAY_ACCOUNT: Alexpux
          PACMAN_REPOSITORY_NAME: ci.mingw
      - task: PublishBuildArtifacts@1
        displayName: Publish packages
        continueOnError: true
        condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/artifacts
          artifactName: mingw-$(MINGW_ARCH)
