post_install() {
  [[ -f mingw32/bin/gtk-update-icon-cache.exe ]] && {
    mingw32/bin/gtk-update-icon-cache -q -t -f mingw32/share/icons/Adwaita
  }
  [[ -f mingw32/bin/gtk-update-icon-cache-3.0.exe ]] && {
    mingw32/bin/gtk-update-icon-cache-3.0 -q -t -f mingw32/share/icons/Adwaita
  }
  [[ -f mingw32/bin/gdk-pixbuf-query-loaders.exe ]] && {
    mingw32/bin/gdk-pixbuf-query-loaders.exe --update-cache
  }
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
