MINGW_INSTALL=mingw64

post_install() {
  [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache.exe ]] && {
    ${MINGW_INSTALL}/bin/gtk-update-icon-cache -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
  }
  [[ -f ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0.exe ]] && {
    ${MINGW_INSTALL}/bin/gtk-update-icon-cache-3.0 -q -t -f ${MINGW_INSTALL}/share/icons/Adwaita
  }
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
