post_install() {
  cat << _EOF

  Fontconfig configuration is done via /mingw32/etc/fonts/conf.avail and conf.d.
  Read /mingw32/etc/fonts/conf.d/README for more information.

_EOF

  echo -n "updating font cache... "
  mingw32/bin/fc-cache -f
  echo "done."
}

post_upgrade() {
  echo -n "updating font cache... "
  mingw32/bin/fc-cache -f
  echo "done."
}

post_remove() {
  cat << _EOF

  Check for dead symlinks and leftover files
  in mingw32/etc/fonts/conf.d/

_EOF
}