#!/usr/bin/env bash

if [[ "$1" == "shared" ]]; then
  echo "Building shared"
elif [[ "$1" == "static" ]]; then
  echo "Building static"
else
  echo "${0} :: Error :: Please pass static or shared"
  exit 1
fi

THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Listed in tier-order
declare -a pkgs=(
extra-cmake-modules
breeze-icons-qt5
oxygen-icons-qt5
kapidox-qt5
attica-qt5
karchive-qt5
threadweaver-qt5
kcodecs-qt5
kconfig-qt5
kcoreaddons-qt5
kdbusaddons-qt5
kguiaddons-qt5
ki18n-qt5
kwindowsystem-qt5
kcrash-qt5
kglobalaccel-qt5
kidletime-qt5
kimageformats-qt5
kitemmodels-qt5
kitemviews-qt5
kdoctools-qt5
kjs-qt5
kplotting-qt5
kwidgetsaddons-qt5
kservice-qt5
solid-qt5
kauth-qt5
kconfigwidgets-qt5
kiconthemes-qt5
kcompletion-qt5
sonnet-qt5
ktextwidgets-qt5
kxmlgui-qt5
kbookmarks-qt5
kjobwidgets-qt5
phonon-qt5
knotifications-qt5
kemoticons-qt5
kdewebkit-qt5
knotifyconfig-qt5
kwallet-qt5
kio-qt5
kparts-qt5
ktexteditor-qt5
knewstuff-qt5
kpackage-qt5
kdeclarative-qt5
kcmutils-qt5
kinit-qt5
kactivities-qt5
kfilemetadata-qt5
#kpeople-qt5
#ktpy-qt5
plasma-framework-qt5
krunner-qt5
strigi
baloo-qt5
kdesignerplugin-qt5
kunitconversion-qt5
kdewin-qt5
kded-qt5
kdelibs4support-qt5
kthml-qt5
kjsembed-qt5
kmediaplayer-qt5
kross-qt5
)

for pkg in "${pkgs[@]}"; do
  pushd ${THISDIR}/../mingw-w64-${pkg}
  export KF5_VARIANT=$1
  rm -rf *pkg*xz src pkg
  makepkg-mingw -siLf --noconfirm || exit 1
  popd
done
