#!/usr/bin/env bash

if [[ "$1" == "shared" ]]; then
  echo "Building shared"
elif [[ "$1" == "static" ]]; then
  echo "Building static"
else
  echo "${0} :: Error :: Please pass static or shared"
  exit 1
fi

THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Listed in tier-order
declare -a pkgs=(
baloo-widgets-qt5
#doplhin-qt5  #FIXME: undefined reference to `_imp___*'
kate-qt5
)

for pkg in "${pkgs[@]}"; do
  pushd ${THISDIR}/../mingw-w64-${pkg}
  export KF5_VARIANT=$1
  rm -rf *pkg*xz src pkg
  makepkg-mingw -siLf --noconfirm || exit 1
  popd
done
