name: Bug Report
description: Submit a bug report.
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is, and why you consider it to be a bug.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Verification
      description: Please verify that you've followed these steps.
      options:
        - label: I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)
          required: true
  - type: textarea
    attributes:
      label: Windows Version
      description: Please run `cmd.exe /c ver` to get the build of Windows you are on.
      placeholder: "Microsoft Windows [Version 10.0.19042.867]"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: MINGW environments affected
      description: The environment name can be found in shell prompt. Or run `echo $MSYSTEM` to get the MINGW environment.
      options:
        - label: MINGW64
        - label: MINGW32
        - label: UCRT64
        - label: CLANG64
        - label: CLANG32
        - label: CLANGARM64
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: A description of what is actually happening.
    validations:
        required: true
  - type: textarea
    attributes:
      label: Repro steps
      placeholder: |
        A description with steps to reproduce the issue.
        1. Step 1
        2. Step 2
    validations:
        required: true
  - type: input
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!
