name: Package request
description: Request a new package
title: Add [package name]
labels: [package-request]
body:
  - type: input
    attributes:
      label: Package name
    validations:
      required: true
  - type: textarea
    attributes:
      label: Brief description of package
  - type: input
    attributes:
      label: URL for package's homepage
  - type: textarea
    attributes:
      label: Provide a basic test case to validate the package's functionality.
  - type: checkboxes
    attributes:
      label: MINGW environments where you need the package
      options:
        - label: MINGW64
        - label: MINGW32
        - label: UCRT64
        - label: CLANG64
        - label: CLANG32
        - label: CLANGARM64
  - type: input
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!
