name: Update request
description: Request an update to an existing package
title: "[package name] update to <version>"
labels: [update-request]
body:
  - type: input
    attributes:
      label: Package name
    validations:
      required: true
  - type: input
    attributes:
      label: New version number
  - type: textarea
    attributes:
      label: Other information that may be useful
      description:  release notes, etc...!
  - type: input
    attributes:
      label: Are you willing to submit a PR?
      description: We accept contributions!
