post_install() {
  cd ucrt64
  local _prefix=$(pwd -W)
  cd -
  local _it
# "somepackage" should be replaced with the name of your .EXE w/o 2 and .exe ext
# Like this:
# For "myexe.exe", it would be "myexe" .
  for _it in sip-build sip-distinfo sip-install sip-module sip-sdist sip-wheel; do
    sed -e "s|/ucrt64|${_prefix}|g" \
        -i ${_prefix}/bin/${_it}-script.py
  done
}

post_upgrade() {
  post_install
}
