post_install() {
# We have to use DOS pathes in ocaml.  These have to be customized to
# the end user's system installation.  
#This is stolen from ocaml-findlib's tools/patch file.
  _varvalue="$(cygpath -w -l /mingw32/lib/ocaml)"
  _varvalue="$(echo "$_varvalue" | sed -e 's;\\;\\\\\\\\;g')"
    # e.g. c:\file is transformed to c:\\\\file
  sed -e "s;/mingw32/lib/ocaml;${_varvalue};g" -i /mingw32/etc/findlib.conf
}

post_upgrade() {
  post_install
}
