MINGW_INSTALL=mingw64

post_remove() {
  if [ -d ${MINGW_INSTALL}/share/mime ]; then
    rm -f ${MINGW_INSTALL}/share/mime/{globs,globs2,icons,treemagic,generic-icons,types,magic,XMLnamespaces,subclasses,aliases,mime.cache}
    rm -rf ${MINGW_INSTALL}/share/mime/{application,audio,image,inode,message,model,multipart,text,video,x-content,x-epoc}
    rmdir --ignore-fail-on-non-empty ${MINGW_INSTALL}/share/mime
  fi
}
