post_install() {
  mingw32/bin/gtk4-update-icon-cache.exe -q -t -f mingw32/share/icons/hicolor
  mingw32/bin/gtk4-update-icon-cache.exe -q -t -f mingw32/share/icons/Adwaita
  mingw32/bin/glib-compile-schemas.exe mingw32/share/glib-2.0/schemas
}

post_upgrade() {
  post_install
}

post_remove() {
  mingw32/bin/glib-compile-schemas.exe mingw32/share/glib-2.0/schemas
  mingw32/bin/gtk4-update-icon-cache.exe -q -t -f mingw32/share/icons/hicolor
  mingw32/bin/gtk4-update-icon-cache.exe -q -t -f mingw32/share/icons/Adwaita
}
