post_install() {
  mingw64/bin/gtk4-update-icon-cache.exe -q -t -f mingw64/share/icons/hicolor
  mingw64/bin/gtk4-update-icon-cache.exe -q -t -f mingw64/share/icons/Adwaita
  mingw64/bin/glib-compile-schemas.exe mingw64/share/glib-2.0/schemas
}

post_upgrade() {
  post_install
}

post_remove() {
  mingw64/bin/glib-compile-schemas.exe mingw64/share/glib-2.0/schemas
  mingw64/bin/gtk4-update-icon-cache.exe -q -t -f mingw64/share/icons/hicolor
  mingw64/bin/gtk4-update-icon-cache.exe -q -t -f mingw64/share/icons/Adwaita
}
