PYTHON_SITELIB=/mingw64/lib/python2.7/site-packages

post_install() {
  if test ! -f mingw64/etc/xml/catalog; then
    usr/bin/mkdir -p mingw64/etc/xml
    mingw64/bin/xmlcatalog --noout --create mingw64/etc/xml/catalog
  fi

  if test -f mingw64/bin/python2.exe; then
    mingw64/bin/python2.exe -m compileall -q -f ${PYTHON_SITELIB}/*libxml2.py
    mingw64/bin/python2.exe -OO -m compileall -q -f ${PYTHON_SITELIB}/*libxml2.py
  fi
}

post_upgrade() {
  post_install
}
