PYTHON_SITELIB=/mingw32/lib/python2.7/site-packages

post_install() {
  if test ! -f mingw32/etc/xml/catalog; then
    bin/mkdir -p mingw32/etc/xml
    mingw32/bin/xmlcatalog --noout --create mingw32/etc/xml/catalog
  fi

  if test -f mingw32/bin/python2.exe; then
    mingw32/bin/python2.exe -m compileall -q -f ${PYTHON_SITELIB}/*libxml2.py
    mingw32/bin/python2.exe -OO -m compileall -q -f ${PYTHON_SITELIB}/*libxml2.py
  fi
}

post_upgrade() {
  post_install
}
