--- Makefile.orig	2014-03-13 13:18:11.000000000 +0400
+++ Makefile	2014-07-24 11:44:56.382400000 +0400
@@ -19,7 +19,7 @@
 # IN THE SOFTWARE.
 
 PLATFORM ?= $(shell sh -c 'uname -s | tr "[A-Z]" "[a-z]"')
-SONAME ?= libhttp_parser.so.2.5.0
+SONAME ?= libhttp_parser-2.dll
 
 CC?=gcc
 AR?=ar
@@ -33,9 +33,7 @@
 CFLAGS_DEBUG = $(CFLAGS) -O0 -g $(CFLAGS_DEBUG_EXTRA)
 CFLAGS_FAST = $(CFLAGS) -O3 $(CFLAGS_FAST_EXTRA)
 CFLAGS_BENCH = $(CFLAGS_FAST) -Wno-unused-parameter
-CFLAGS_LIB = $(CFLAGS_FAST) -fPIC
-
-LDFLAGS_LIB = $(LDFLAGS) -shared
+LDFLAGS_LIB = $(LDFLAGS) -shared -Wl,--out-implib=libhttp_parser.dll.a
 
 INSTALL ?= install
 PREFIX ?= $(DESTDIR)/usr/local
