post_install() {
  mkdir -p mingw64/lib/gtk-3.0
  mingw64/bin/gtk-query-immodules-3.0.exe > mingw64/lib/gtk-3.0/immodules.cache
  mingw64/bin/gtk-update-icon-cache-3.0 -q -t -f mingw64/share/icons/hicolor
  mingw64/bin/gtk-update-icon-cache-3.0 -q -t -f mingw64/share/icons/Adwaita
  mingw64/bin/glib-compile-schemas.exe mingw64/share/glib-2.0/schemas
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -f mingw64/lib/gtk-3.0/immodules.cache
  mingw64/bin/glib-compile-schemas.exe mingw64/share/glib-2.0/schemas
  mingw64/bin/gtk-update-icon-cache-3.0 -q -t -f mingw64/share/icons/hicolor
  mingw64/bin/gtk-update-icon-cache-3.0 -q -t -f mingw64/share/icons/Adwaita
}
